services:
  blog:
    build: .
    image: personal-blog:latest
    container_name: personal-blog
    restart: unless-stopped
    ports:
      - "8080:80"
      # - "443:443"  # HTTPS端口，需要SSL证书时取消注释
    volumes:
      # 挂载日志目录到宿主机，方便查看访问日志
      - ./logs:/var/log/nginx
      # SSL证书目录（如果需要HTTPS）
      # - ./ssl:/etc/nginx/ssl:ro
    environment:
      - TZ=Asia/Shanghai
      - NGINX_HOST=43.143.124.38
      - NGINX_PORT=8080
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/home/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Traefik标签（如果使用反向代理）
    labels:
      - "traefik.enable=false"
      # 如果有域名，可以启用下面的配置
      # - "traefik.http.routers.blog.rule=Host(`yourdomain.com`)"
      # - "traefik.http.routers.blog.entrypoints=websecure"
      # - "traefik.http.routers.blog.tls.certresolver=letsencrypt"

networks:
  blog-network:
    driver: bridge

# 如果需要持久化存储，可以添加volumes配置
volumes:
  nginx-logs:
    driver: local
